# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# SUDO completion
complete -cf sudo

# system upgrade
alias upgrade='sudo pacman -Syu --noconfirm'

# emacs without X
alias nxemacs='emacs --nw'
